services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8000:8000"
    environment:
      SERVER_PORT: "8000"
      CONSUL_ADDR: consul-server:8500
    networks:
      - consul-network
      - gateway-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--tries=1", "-O", "/dev/null", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  consul-network:
    external: true
  gateway-network:
    driver: bridge